name: PageSpeed Report for hosseini-rtr.ir
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Store your API key in repository secrets as PAGESPEED_TOKEN
          plugin_pagespeed_url: https://hosseini-rtr.ir/
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
